import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import Footer from '../components/Footer'
import Table from '../components/Table'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <main className='relative mx-auto max-w-3xl bg-white min-h-screen'>
      <Head>
        <title>Kiffel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <Table />

      

      <Footer />
    </main>
  )
}
